package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/ncondes/go/social/docs" // docs is generated by Swag CLI, you have to run `swag init` command
	"github.com/ncondes/go/social/internal/config"
	"github.com/ncondes/go/social/internal/handlers"
	httpSwagger "github.com/swaggo/http-swagger"
)

type application struct {
	config   *config.Config
	handlers *handlers.Handlers
}

func (app *application) mount() *chi.Mux {
	r := chi.NewRouter()

	r.Use(middleware.RequestID) // Add a request ID to the context
	r.Use(middleware.RealIP)    // Get the real IP address of the client
	r.Use(middleware.Logger)    // Log the request
	r.Use(middleware.Recoverer) // Recover from panics without crashing the server

	// Set a timeout value on the request context (ctx), that will signal
	// through ctx.Done() that the request has timed out and further
	// processing should be stopped.
	r.Use(middleware.Timeout(60 * time.Second))

	r.Route("/v1", func(r chi.Router) {
		r.Get("/health", app.handlers.HealthHandler.Check)

		docsURL := fmt.Sprintf("%s/swagger/doc.json", app.config.Addr)
		r.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL(docsURL),
		))

		r.Route("/feed", func(r chi.Router) {
			// TODO: middleware for authentication
			r.Get("/", app.handlers.FeedHandler.GetUserFeed)
		})

		r.Route("/users", func(r chi.Router) {
			r.Post("/", app.handlers.UserHandler.CreateUser) // TODO: remove?

			r.Route("/{userID}", func(r chi.Router) {
				r.Use(handlers.UserIDMiddleware)

				r.Get("/", app.handlers.UserHandler.GetUser)
				r.Post("/follow", app.handlers.UserHandler.FollowUser)
				r.Delete("/unfollow", app.handlers.UserHandler.UnfollowUser)
			})
		})

		r.Route("/posts", func(r chi.Router) {
			r.Post("/", app.handlers.PostHandler.CreatePost)

			r.Route("/{postID}", func(r chi.Router) {
				r.Use(handlers.PostIDMiddleware)

				r.Get("/", app.handlers.PostHandler.GetPost)
				r.Patch("/", app.handlers.PostHandler.UpdatePost)
				r.Delete("/", app.handlers.PostHandler.DeletePost)

				r.Route("/comments", func(r chi.Router) {
					r.Post("/", app.handlers.CommentHandler.CreateComment)
					r.Get("/", app.handlers.CommentHandler.GetCommentsByPostID)
				})
			})
		})
	})

	return r
}

func (app *application) run(mux *chi.Mux) error {

	docs.SwaggerInfo.Host = app.config.APIBaseURL
	docs.SwaggerInfo.BasePath = "/v1"
	docs.SwaggerInfo.Version = version

	srv := &http.Server{
		Addr:         app.config.Addr,
		Handler:      mux,
		WriteTimeout: 30 * time.Second,
		ReadTimeout:  10 * time.Second,
		IdleTimeout:  1 * time.Minute,
	}

	log.Printf("Starting server on %s\n", app.config.Addr)

	return srv.ListenAndServe()
}
