package main

import (
	"context"
	"expvar"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	"github.com/ncondes/go/social/docs" // docs is generated by Swag CLI, you have to run `swag init` command
	"github.com/ncondes/go/social/internal/auth"
	"github.com/ncondes/go/social/internal/config"
	"github.com/ncondes/go/social/internal/handlers"
	"github.com/ncondes/go/social/internal/logging"
	"github.com/ncondes/go/social/internal/metrics"
	"github.com/ncondes/go/social/internal/services"
	httpSwagger "github.com/swaggo/http-swagger"
)

type application struct {
	config        *config.Config
	handlers      *handlers.Handlers
	logger        logging.Logger
	authenticator *auth.JWTAuthenticator
	services      *services.Services
	rateLimiters  *RateLimiters
	metrics       *metrics.Metrics
}

func (app *application) mount() *chi.Mux {
	r := chi.NewRouter()

	r.Use(middleware.RequestID) // Add a request ID to the context
	r.Use(middleware.RealIP)    // Get the real IP address of the client
	r.Use(middleware.Logger)    // Log the request
	r.Use(middleware.Recoverer) // Recover from panics without crashing the server

	// Set a timeout value on the request context (ctx), that will signal
	// through ctx.Done() that the request has timed out and further
	// processing should be stopped.
	r.Use(middleware.Timeout(30 * time.Second))
	// Global rate limit - protect server from total overload
	r.Use(handlers.RateLimitMiddleware(app.rateLimiters.Global, app.logger))
	// Metrics middleware
	r.Use(handlers.MetricsMiddleware(app.metrics))

	r.Use(cors.Handler(cors.Options{
		// Configure allowed origins for production (use env var)
		// Current config is meant to be used for local development
		AllowedOrigins:   []string{"https://*", "http://*"},
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: false,
		MaxAge:           300, // Maximum value not ignored by any of major browsers
	}))

	r.Route("/v1", func(r chi.Router) {
		// r.With(handlers.BasicAuthMiddleware(app.logger, app.config)).Get("/health", app.handlers.HealthHandler.Check)

		r.Get("/health", app.handlers.HealthHandler.Check)
		r.Get("/metrics", expvar.Handler().ServeHTTP)

		// Build full swagger doc URL with scheme
		apiBaseURL := app.config.APIBaseURL
		if len(apiBaseURL) < 4 || apiBaseURL[:4] != "http" {
			scheme := "http://"
			if app.config.Env == "production" {
				scheme = "https://"
			}
			apiBaseURL = scheme + apiBaseURL
		}
		docsURL := fmt.Sprintf("%s/v1/swagger/doc.json", apiBaseURL)
		r.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL(docsURL),
		))

		// Auth routes - strict IP-based rate limiting
		r.Group(func(r chi.Router) {
			r.Use(handlers.RateLimitByIPMiddleware(app.rateLimiters.StrictIP, app.logger))

			r.Route("/auth", func(r chi.Router) {
				r.Post("/register", app.handlers.AuthHandler.RegisterUser)
				r.Put("/activate", app.handlers.AuthHandler.ActivateUser)
				r.Post("/token", app.handlers.AuthHandler.GenerateToken)
			})
		})

		// Feed - read operations with generous limits
		r.Route("/feed", func(r chi.Router) {
			r.Use(handlers.AuthTokenMiddleware(
				app.authenticator,
				app.services.UserService,
				app.logger,
			))
			r.Use(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.ReadOps, app.logger))
			r.Get("/", app.handlers.FeedHandler.GetUserFeed)
		})

		r.Route("/users", func(r chi.Router) {

			r.Route("/{userID}", func(r chi.Router) {
				r.Use(handlers.AuthTokenMiddleware(
					app.authenticator,
					app.services.UserService,
					app.logger,
				))
				r.Use(handlers.UserIDMiddleware(app.logger))

				// Read operations
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.ReadOps, app.logger)).Get("/", app.handlers.UserHandler.GetUser)

				// Write operations
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Post("/follow", app.handlers.UserHandler.FollowUser)
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Delete("/unfollow", app.handlers.UserHandler.UnfollowUser)
			})
		})

		r.Route("/posts", func(r chi.Router) {
			r.Use(handlers.AuthTokenMiddleware(
				app.authenticator,
				app.services.UserService,
				app.logger,
			))

			// Create post - write operations
			r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Post("/", app.handlers.PostHandler.CreatePost)

			r.Route("/{postID}", func(r chi.Router) {
				r.Use(handlers.PostIDMiddleware(app.logger))

				// Read operations
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.ReadOps, app.logger)).Get("/", app.handlers.PostHandler.GetPost)

				// Write operations
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Patch("/", app.handlers.PostHandler.UpdatePost)
				r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Delete("/", app.handlers.PostHandler.DeletePost)

				r.Route("/comments", func(r chi.Router) {
					// Write operations
					r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.WriteOps, app.logger)).Post("/", app.handlers.CommentHandler.CreateComment)
					// Read operations
					r.With(handlers.RateLimitByAuthenticatedUserMiddleware(app.rateLimiters.ReadOps, app.logger)).Get("/", app.handlers.CommentHandler.GetCommentsByPostID)
				})
			})
		})
	})

	return r
}

func (app *application) run(mux *chi.Mux) error {
	docs.SwaggerInfo.Host = app.config.APIBaseURL
	docs.SwaggerInfo.BasePath = "/v1"
	docs.SwaggerInfo.Version = version

	srv := &http.Server{
		Addr:         app.config.Addr,
		Handler:      mux,
		WriteTimeout: 30 * time.Second,
		ReadTimeout:  10 * time.Second,
		IdleTimeout:  1 * time.Minute,
	}

	// Channel to listen for OS interrupt signals
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	// Channel to receive server errors
	serverErrors := make(chan error, 1)

	// Start server in a goroutine so we can listen for shutdown signals concurrently
	go func() {
		app.logger.Infow("Starting server", "addr", app.config.Addr)
		serverErrors <- srv.ListenAndServe()
	}()

	// Block until we receive an interrupt signal or server error
	select {
	case err := <-serverErrors:
		// Server failed to start or encountered an error
		if err != nil {
			return fmt.Errorf("server error: %w", err)
		}

	case sig := <-quit:
		// Received shutdown signal (Ctrl+C or kill command)
		app.logger.Infow("Shutting down server...", "signal", sig.String())

		// Create context with 5-second timeout for graceful shutdown
		// This gives in-flight requests time to complete
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()

		// Attempt graceful shutdown
		if err := srv.Shutdown(ctx); err != nil {
			// If graceful shutdown fails, force close the server
			srv.Close()
			return fmt.Errorf("server shutdown failed: %w", err)
		}

		app.logger.Infow("Server stopped gracefully")
	}

	return nil
}
