package db

const (
	usersAmount    = 200
	postsAmount    = 1000
	commentsAmount = 5000
)

var seedFirstNames = []string{
	"James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda",
	"William", "Barbara", "David", "Elizabeth", "Richard", "Susan", "Joseph", "Jessica",
	"Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa",
	"Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley",
	"Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle",
	"Kenneth", "Carol", "Kevin", "Amanda", "Brian", "Dorothy", "George", "Melissa",
	"Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon",
	"Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy",
	"Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda",
	"Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen",
	"Benjamin", "Samantha", "Samuel", "Katherine", "Raymond", "Christine", "Gregory", "Debra",
	"Frank", "Rachel", "Alexander", "Carolyn", "Patrick", "Janet", "Jack", "Catherine",
	"Dennis", "Maria", "Jerry", "Heather", "Tyler", "Diane",
}

var seedLastNames = []string{
	"Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
	"Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas",
	"Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White",
	"Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young",
	"Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
	"Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
	"Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker",
	"Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy",
	"Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey",
	"Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
	"Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza",
	"Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers",
	"Long", "Ross", "Foster", "Jimenez",
}

var seedPostTitles = []string{
	// Technology & Programming
	"Getting Started with Go", "Understanding Microservices", "Best Practices for REST APIs",
	"Introduction to Docker", "Mastering Git Workflows", "Database Design Patterns",
	"Clean Code Principles", "Testing Strategies in Go", "Building Scalable Systems",
	"API Security Best Practices", "Concurrency in Go", "Error Handling Techniques",

	// Cooking & Food
	"Perfect Homemade Pizza Recipe", "Mastering French Pastries", "Quick Weeknight Dinners",
	"The Art of Sourdough Bread", "Vegan Comfort Food Ideas", "Asian Fusion Cooking",
	"Meal Prep for Busy Professionals", "Grilling Tips and Tricks", "Baking Without Gluten",
	"Farm to Table Philosophy", "Fermentation for Beginners", "Chocolate Dessert Masterclass",

	// Travel & Adventure
	"Backpacking Through Southeast Asia", "Hidden Gems in Europe", "Solo Travel Safety Tips",
	"Budget-Friendly Travel Hacks", "Best Hiking Trails in America", "Cultural Etiquette Guide",
	"Digital Nomad Lifestyle", "Photography Tips for Travelers", "Off the Beaten Path Destinations",
	"Sustainable Tourism Practices", "Road Trip Planning Guide", "Adventure Sports Around the World",

	// Fitness & Health
	"Building Muscle After 40", "Yoga for Beginners", "Marathon Training Plan",
	"Nutrition Myths Debunked", "Mental Health and Exercise", "Home Workout Routines",
	"Recovery and Rest Days", "Strength Training for Women", "Cardio vs Weight Training",
	"Mindful Eating Habits", "Sleep Optimization Tips", "Injury Prevention Strategies",

	// Art & Creativity
	"Watercolor Painting Basics", "Digital Art Workflow", "Photography Composition Rules",
	"Creative Writing Prompts", "Music Theory Fundamentals", "Pottery for Beginners",
	"Graphic Design Principles", "Film Photography Revival", "Abstract Art Techniques",
	"Calligraphy and Hand Lettering", "Portrait Drawing Guide", "Street Art Culture",

	// Business & Finance
	"Starting Your First Business", "Investment Strategies for Beginners", "Personal Finance 101",
	"Passive Income Ideas", "Negotiation Skills", "Building a Personal Brand",
	"Stock Market Basics", "Real Estate Investing", "Freelancing Success Tips",
	"Retirement Planning Guide", "Cryptocurrency Explained", "Side Hustle Ideas",

	// Lifestyle & Home
	"Minimalist Living Benefits", "Indoor Plant Care Guide", "Home Organization Hacks",
	"Sustainable Living Tips", "DIY Home Improvements", "Interior Design on a Budget",
	"Zero Waste Lifestyle", "Capsule Wardrobe Essentials", "Feng Shui Principles",
	"Gardening for Small Spaces", "Eco-Friendly Cleaning", "Smart Home Technology",

	// Education & Learning
	"Learning a New Language", "Study Techniques That Work", "Online Course Recommendations",
	"Speed Reading Methods", "Memory Improvement Tips", "Critical Thinking Skills",
	"Teaching Kids at Home", "STEM Education Importance", "Lifelong Learning Benefits",
	"Note-Taking Strategies", "Time Management for Students", "Research Skills Guide",

	// Science & Nature
	"Climate Change Explained", "Space Exploration Updates", "Ocean Conservation Efforts",
	"Wildlife Photography Tips", "Renewable Energy Future", "Astronomy for Beginners",
	"Understanding Ecosystems", "Genetic Engineering Ethics", "Natural Disaster Preparedness",
	"Bird Watching Guide", "Marine Biology Wonders", "Sustainable Agriculture",
}

var seedPostContents = []string{
	"This is a comprehensive guide to help you understand the fundamentals and best practices.",
	"In this post, we'll explore various techniques and patterns that can improve your workflow.",
	"Let me share some insights I've gained from years of experience in this field.",
	"Here are some practical examples and step-by-step instructions to illustrate the key concepts.",
	"This tutorial will walk you through detailed explanations with real-world applications.",
	"I've compiled a list of resources and tools that have been incredibly helpful in my journey.",
	"Today we're diving deep into advanced topics that will take your skills to the next level.",
	"Learn how to avoid common pitfalls and mistakes that many people encounter.",
	"This article covers everything you need to know to get started with confidence.",
	"Discover the latest trends and innovations that are shaping the future of this industry.",
	"A detailed analysis of different approaches and their trade-offs in real-world scenarios.",
	"Practical tips and tricks that you can immediately apply to your daily routine.",
	"Understanding the underlying principles will help you make better informed decisions.",
	"This guide includes comparisons, recommendations, and lessons from extensive experience.",
	"Explore the ecosystem and learn about the most popular methods and approaches.",
	"Real-world case studies demonstrating how these concepts are applied successfully.",
	"A beginner-friendly introduction with clear examples and easy-to-follow instructions.",
	"Advanced techniques for optimizing your results and improving overall quality.",
	"Common questions answered with detailed explanations and working examples.",
	"Best practices from experts and lessons learned from successful projects.",
	"After trying countless methods, I've finally found what works best for most people.",
	"The journey wasn't easy, but these strategies made all the difference in my progress.",
	"I wish someone had told me these things when I first started out years ago.",
	"Breaking down complex topics into simple, digestible pieces that anyone can understand.",
	"My personal experience with this has been transformative and eye-opening.",
	"These are the exact steps I followed to achieve consistent results over time.",
	"Don't make the same mistakes I did - learn from my failures and successes.",
	"A comprehensive breakdown of everything you need to consider before getting started.",
	"The science behind why this works and how you can apply it effectively.",
	"Comparing different methods to help you choose what's right for your situation.",
	"This changed my perspective completely and I hope it does the same for you.",
	"Evidence-based approaches that have been proven to work time and time again.",
	"Simple yet powerful strategies that deliver remarkable results when applied consistently.",
	"What I learned from interviewing dozens of experts in this field.",
	"The ultimate resource guide with everything you need in one convenient place.",
	"Debunking common myths and misconceptions that hold people back from success.",
	"A fresh perspective on an old topic that challenges conventional wisdom.",
	"Innovative solutions to problems that have plagued this field for years.",
	"How to get started today with minimal investment and maximum impact.",
	"The complete roadmap from beginner to advanced practitioner in clear steps.",
	"Insider secrets that professionals use but rarely share publicly.",
	"Why most people fail at this and how you can be different.",
	"The psychology behind success and how to leverage it for better outcomes.",
	"Sustainable approaches that work long-term, not just quick fixes.",
	"Building a strong foundation that will serve you for years to come.",
	"Connecting theory with practice through hands-on examples and exercises.",
	"The most important lessons I've learned after years of dedication.",
	"How to overcome obstacles and stay motivated during challenging times.",
	"Creating lasting change through small, consistent actions every day.",
	"The power of community and collaboration in achieving your goals.",
	"Balancing different priorities while maintaining focus on what matters most.",
	"Adapting to change and staying relevant in an evolving landscape.",
	"The role of mindset in determining success or failure in any endeavor.",
	"Practical frameworks you can use to organize your thoughts and actions.",
	"How to measure progress and adjust your approach based on results.",
	"The importance of patience and persistence in mastering any skill.",
	"Learning from failures and using them as stepping stones to success.",
	"Building habits that support your long-term vision and aspirations.",
	"The intersection of passion and practicality in pursuing your interests.",
	"How to find your unique voice and stand out in a crowded space.",
	"Collaboration strategies that amplify individual efforts exponentially.",
	"The value of continuous improvement and never settling for mediocrity.",
	"How to balance ambition with contentment and avoid burnout.",
	"Creating systems that work for you instead of against you.",
	"The art of simplification in an increasingly complex world.",
	"Why diversity of thought leads to better solutions and outcomes.",
	"How to cultivate curiosity and maintain a beginner's mindset.",
	"The importance of rest and recovery in any intensive pursuit.",
	"Building resilience through challenges and setbacks over time.",
	"How to leverage technology without becoming dependent on it.",
	"The role of intuition in decision-making alongside analytical thinking.",
	"Creating win-win situations through empathy and understanding.",
	"How to set realistic goals while still dreaming big.",
	"The power of storytelling in connecting with others meaningfully.",
	"Why authenticity matters more than perfection in today's world.",
	"How to navigate uncertainty with confidence and grace.",
	"The importance of giving back and contributing to your community.",
	"Building bridges between different perspectives and backgrounds.",
	"How to maintain work-life balance in demanding environments.",
	"The value of mentorship in accelerating personal growth.",
	"Creating positive change through individual and collective action.",
	"How to stay grounded while pursuing ambitious goals.",
	"The intersection of tradition and innovation in modern practice.",
	"Why lifelong learning is essential in our rapidly changing world.",
	"How to find meaning and purpose in everyday activities.",
	"The importance of self-awareness in personal development.",
	"Building strong relationships through genuine connection.",
	"How to embrace failure as a necessary part of growth.",
	"The role of creativity in problem-solving across all domains.",
	"Why consistency beats intensity in achieving lasting results.",
	"How to develop critical thinking skills in the age of information.",
	"The power of visualization in manifesting desired outcomes.",
	"Building confidence through competence and continuous practice.",
	"How to navigate criticism constructively and grow from feedback.",
	"The importance of celebrating small wins along the journey.",
	"Creating sustainable momentum through strategic planning.",
	"How to find inspiration in unexpected places and situations.",
	"The value of experimentation in discovering what works for you.",
	"Why patience is truly a virtue in any worthwhile pursuit.",
}

var seedPostTags = []string{
	// Technology
	"golang", "programming", "webdev", "api", "database", "docker", "kubernetes",
	"microservices", "testing", "security", "devops", "cloud", "backend", "frontend",

	// Food & Cooking
	"cooking", "recipe", "baking", "vegan", "vegetarian", "healthy", "foodie",
	"dessert", "breakfast", "dinner", "meal-prep", "nutrition", "culinary", "gourmet",

	// Travel
	"travel", "adventure", "backpacking", "photography", "culture", "wanderlust",
	"solo-travel", "budget-travel", "hiking", "camping", "roadtrip", "tourism",

	// Fitness & Health
	"fitness", "health", "workout", "yoga", "running", "gym", "nutrition",
	"wellness", "mindfulness", "meditation", "mental-health", "strength-training",

	// Art & Creativity
	"art", "photography", "design", "creative", "painting", "drawing", "music",
	"writing", "poetry", "crafts", "diy", "handmade", "illustration", "digital-art",

	// Business & Finance
	"business", "finance", "investing", "entrepreneurship", "startup", "marketing",
	"productivity", "career", "money", "freelance", "passive-income", "crypto",

	// Lifestyle
	"lifestyle", "minimalism", "sustainability", "home", "organization", "fashion",
	"beauty", "self-care", "relationships", "parenting", "pets", "gardening",

	// Education & Learning
	"education", "learning", "teaching", "study", "books", "language", "science",
	"history", "philosophy", "psychology", "research", "academic", "tutorial",

	// Nature & Environment
	"nature", "environment", "wildlife", "conservation", "climate", "ecology",
	"outdoors", "animals", "plants", "sustainability", "green-living", "renewable",

	// Entertainment
	"movies", "gaming", "sports", "music", "books", "tv-shows", "anime",
	"entertainment", "hobbies", "fun", "comedy", "drama",
}

var seedCommentContents = []string{
	"Great post! Thanks for sharing this valuable information.",
	"This is exactly what I was looking for. Very helpful!",
	"Interesting perspective. I learned something new today.",
	"Could you elaborate more on this topic? I'd love to know more.",
	"Excellent explanation! Clear and concise.",
	"I have a different approach that also works well in my experience.",
	"Thanks for the detailed tutorial. It helped me solve my problem.",
	"This is a must-read for anyone interested in this topic.",
	"Well written and easy to follow. Keep up the good work!",
	"I disagree with some points, but overall a solid article.",
	"Bookmarking this for future reference. Very useful!",
	"Can you provide more examples? That would be really helpful.",
	"I've been struggling with this, and your post clarified everything.",
	"Amazing content! Looking forward to more posts like this.",
	"This should be shared more widely. So valuable!",
	"I tried this approach and it works perfectly. Thanks!",
	"Insightful post. You covered all the important aspects.",
	"Quick question: have you tried this in different scenarios?",
	"Fantastic write-up! Sharing this with my friends.",
	"This helped me understand the concept much better. Appreciate it!",
	"Absolutely love this! More people need to see this.",
	"Your experience really shows through in this post.",
	"I've been following your content for a while. Always top-notch!",
	"This changed my perspective completely. Thank you!",
	"Do you have any recommendations for further reading?",
	"I'm going to try this out and report back with my results.",
	"This is gold! Can't believe this information is free.",
	"Your writing style makes complex topics so accessible.",
	"I wish I had found this post earlier. Would have saved me time!",
	"The examples you provided are really helpful for understanding.",
	"This resonates with me so much. Thank you for sharing!",
	"I have a slightly different take on this, but I see your point.",
	"Could you do a follow-up post diving deeper into this?",
	"This is now my go-to resource for this topic.",
	"I appreciate the time and effort you put into this.",
	"Your passion for this subject really comes through.",
	"I'm inspired to start my own journey after reading this.",
	"This is the kind of content the internet needs more of.",
	"I've shared this with my team. Everyone found it useful!",
	"The practical tips are what make this post stand out.",
	"I love how you broke this down into manageable steps.",
	"This is exactly the motivation I needed today.",
	"Your honesty about the challenges is refreshing.",
	"I'm definitely going to implement these suggestions.",
	"This post deserves way more attention than it's getting.",
	"I've tried similar things before, but your approach is better.",
	"Thank you for being so generous with your knowledge.",
	"This is comprehensive without being overwhelming. Perfect!",
	"I appreciate the balanced perspective you provided.",
	"Your real-world examples make this so much more relatable.",
	"I'm curious about your thoughts on related topics too.",
	"This is going straight into my saved posts collection.",
	"You have a gift for explaining things clearly.",
	"I never thought about it this way before. Mind blown!",
	"This is the push I needed to finally get started.",
	"Your enthusiasm is contagious! Great post.",
	"I love the community you're building around this topic.",
	"This is both informative and entertaining. Rare combination!",
	"I've recommended this to several people already.",
	"Your expertise really shines through in this post.",
	"This is the most helpful thing I've read on this topic.",
	"I appreciate how you addressed common misconceptions.",
	"This post came at the perfect time for me. Thank you!",
	"I love how practical and actionable your advice is.",
	"This is going to be my reference guide going forward.",
	"You've inspired me to share my own experiences too.",
	"The way you structured this makes it so easy to follow.",
	"I'm impressed by the depth of research in this post.",
	"This is exactly the kind of content I subscribed for.",
	"Your personal stories make this so much more engaging.",
	"I've learned more from this post than from entire courses.",
	"This is a game-changer. Thank you for sharing!",
	"I appreciate how you considered different perspectives.",
	"This post is a perfect blend of theory and practice.",
	"I'm going to revisit this post many times. So valuable!",
	"Your writing makes me want to explore this topic further.",
	"This is the most comprehensive guide I've found on this.",
	"I love how you made this accessible to beginners.",
	"This post has already made a difference in my approach.",
	"Thank you for taking the time to share your expertise.",
	"I'm grateful for creators like you who share knowledge freely.",
	"This is the kind of quality content that stands the test of time.",
	"I've been waiting for someone to address this topic properly.",
	"Your unique perspective adds so much value to this discussion.",
	"This post exceeded my expectations. Fantastic work!",
	"I appreciate the nuanced approach you took with this topic.",
	"This is both educational and inspiring. Thank you!",
	"I'm excited to put these ideas into practice.",
	"Your authenticity makes this post so much more impactful.",
	"This is the resource I'll be recommending to everyone.",
	"I love how you challenged conventional thinking here.",
	"This post has sparked so many ideas for me. Thank you!",
	"Your dedication to helping others really shows.",
	"This is the kind of post that makes the internet great.",
	"I'm so glad I stumbled upon this. Life-changing!",
	"Your practical wisdom is exactly what I needed.",
	"This post is a masterclass in clear communication.",
	"I appreciate how you made this topic approachable.",
	"This is going to help so many people. Thank you!",
	"Your insights are always so valuable. Keep it up!",
}

var seedEmailDomains = []string{
	"gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com",
	"protonmail.com", "aol.com", "mail.com", "zoho.com", "fastmail.com",
}
